### ISSUE TITLE
Can't create poll

### ISSUE THREAD

**Issue by Ezerbeth** [TheOnly92/Simple-Poll-Engine#1]
Hello,

When trying to create a poll, I get this error:

[Wed Dec 02 08:14:31.651825 2015] [:error] [pid 63408] [client 127.0.0.1:59477] PHP Fatal error:  Uncaught exception 'Exception' with message 'Incorrect integer value: '' for column 'randomize_order' at row 1' in /usr/www/poll/infrastructure/mysqlihandler.php:80\nStack trace:\n#0 /usr/www/poll/infrastructure/mysqlihandler.php(26): MySQLiStatement->Exec(Array)\n#1 /usr/www/poll/interfaces/repositories.php(16): MySQLiHandler->Exec('INSERT INTO spe...', Array)\n#2 /usr/www/poll/usecases.php(202): DbPollRepository->Store(Object(DomainPoll))\n#3 /usr/www/poll/controllers.php(172): PollInteractor->Create(Object(UsecasesPoll))\n#4 /usr/www/poll/controllers.php(84): AdminHandler->NewPoll()\n#5 /usr/www/poll/index.php(24): AdminHandler->Route('new-poll')\n#6 {main}\n  thrown in /usr/www/poll/infrastructure/mysqlihandler.php on line 80, referer: https://127.0.0.1/poll/index.php?c=admin&a=new-poll

If I leave "randomize" unchecked, then the error is different:
[Wed Dec 02 08:14:57.983167 2015] [:error] [pid 14351] [client 127.0.0.1:54218] PHP Fatal error:  Uncaught exception 'Exception' with message 'Incorrect integer value: '' for column 'closed' at row 1' in /usr/www/poll/infrastructure/mysqlihandler.php:80\nStack trace:\n#0 /usr/www/poll/infrastructure/mysqlihandler.php(26): MySQLiStatement->Exec(Array)\n#1 /usr/www/poll/interfaces/repositories.php(16): MySQLiHandler->Exec('INSERT INTO spe...', Array)\n#2 /usr/www/poll/usecases.php(202): DbPollRepository->Store(Object(DomainPoll))\n#3 /usr/www/poll/controllers.php(172): PollInteractor->Create(Object(UsecasesPoll))\n#4 /usr/www/poll/controllers.php(84): AdminHandler->NewPoll()\n#5 /usr/www/poll/index.php(24): AdminHandler->Route('new-poll')\n#6 {main}\n  thrown in /usr/www/poll/infrastructure/mysqlihandler.php on line 80, referer: https://127.0.0.1/poll/index.php?c=admin&a=new-poll

Any idea?

PHP 5.6.16
MySQL 5.6.27

Thanks!

**Comment by TheOnly92** [comment]
I've made a commit to try to fix this, can you try pulling the latest version?

**Comment by Ezerbeth** [comment]
Wow that was fast!

Same error though:
 Fatal error: Uncaught exception 'Exception' with message 'Incorrect integer value: '' for column 'randomize_order' at row 1' in /usr/www/poll/infrastructure/mysqlihandler.php:80 Stack trace: #0 /usr/www/poll/infrastructure/mysqlihandler.php(26): MySQLiStatement->Exec(Array) #1 /usr/www/poll/interfaces/repositories.php(16): MySQLiHandler->Exec('INSERT INTO spe...', Array) #2 /usr/www/poll/usecases.php(202): DbPollRepository->Store(Object(DomainPoll)) #3 /usr/www/poll/controllers.php(172): PollInteractor->Create(Object(UsecasesPoll)) #4 /usr/www/poll/controllers.php(84): AdminHandler->NewPoll() #5 /usr/www/poll/index.php(24): AdminHandler->Route('new-poll') #6 {main} thrown in /usr/www/poll/infrastructure/mysqlihandler.php on line 80

**Comment by TheOnly92** [comment]
Hmm that's weird, it's code I've written a long time ago and frankly I don't remember the exact details and I don't have the environment right now to test out, so it may take me a few tries to iron things out, but can you try pulling the latest version again?

**Comment by Ezerbeth** [comment]
No worries, I understand.

The new error is:
 Fatal error: Uncaught exception 'Exception' with message 'Field 'image' doesn't have a default value' in /usr/www/poll/infrastructure/mysqlihandler.php:80 Stack trace: #0 /usr/www/poll/infrastructure/mysqlihandler.php(26): MySQLiStatement->Exec(Array) #1 /usr/www/poll/interfaces/repositories.php(26): MySQLiHandler->Exec('INSERT INTO spe...', Array) #2 /usr/www/poll/usecases.php(205): DbPollRepository->StoreAnswer(Object(DomainPollAnswer)) #3 /usr/www/poll/controllers.php(172): PollInteractor->Create(Object(UsecasesPoll)) #4 /usr/www/poll/controllers.php(84): AdminHandler->NewPoll() #5 /usr/www/poll/index.php(24): AdminHandler->Route('new-poll') #6 {main} thrown in /usr/www/poll/infrastructure/mysqlihandler.php on line 80

**Comment by Ezerbeth** [comment]
And thanks for looking into this!

I'll try with older PHP/MySQLi, might solve the issue.

**Comment by TheOnly92** [comment]
Okay, can you please try again? I don't think the version has anything to do with it.

**Comment by Ezerbeth** [comment]
Yes, it works now. Thanks a lot!

**Comment by TheOnly92** [comment]
Great, I'll close this issue then.
